/** Deterministic, auth-free fixtures for the hybrid candidates preview.
 *
 *  Data mirrors the `Kandydaci.dc.html` design comp (realistic PL IT-recruiter
 *  scenario) so the /preview/candidates harness renders the target layout
 *  without any API. `stage` holds the canonical pipeline KEY (not a label) so
 *  it flows through `stageTone`/`stageLabel` exactly like production rows. */
export interface CandidateHybridFixture {
  id: string;
  name: string;
  initials: string;
  role: string;
  location: string;
  email: string;
  phone: string;
  /** Canonical pipeline stage key (see STAGE_LABELS). */
  stage: string;
  stageDate: string;
  owner: string;
  recruitments: number;
  rate: string;
  english: string;
  availability: string;
  workMode: string;
  nationality: string;
  skills: string[];
  headline: string;
  lastNote: string;
  rejectionReason?: string;
  added: string;
}

export const CANDIDATE_HYBRID_FIXTURES: CandidateHybridFixture[] = [
  {
    id: "dawid",
    name: "Dawid Łacheta",
    initials: "DŁ",
    role: "Senior Fullstack Developer",
    location: "Warszawa",
    email: "dawid.lacheta@gmail.com",
    phone: "+48 731 208 445",
    stage: "cv_sent",
    stageDate: "3.07.2026",
    owner: "Marta Kozarewicz",
    recruitments: 4,
    rate: "130 zł/h",
    english: "C1",
    availability: "miesiąc (B2B)",
    workMode: "Hybryda 2×/tydz.",
    nationality: "Polska",
    skills: ["Java", "Spring Boot", "Kafka", "RabbitMQ", "Angular", "React", "Docker", "Kubernetes", "REST API", "SOAP"],
    headline: "Java Developer z ponad 4-letnim doświadczeniem, mocny w Spring Boot i architekturze eventowej (Kafka, RabbitMQ).",
    lastNote: "Zmieniła się motywacja — szuka projektu z nowoczesnym stackiem i realnym wpływem na architekturę. Dostępność miesiąc na B2B.",
    added: "30.06.2026",
  },
  {
    id: "tomasz",
    name: "Tomasz Puchalski",
    initials: "TP",
    role: "Senior Java Developer",
    location: "Warszawa",
    email: "t.puchalski@outlook.com",
    phone: "+48 604 991 273",
    stage: "rejected",
    stageDate: "30.06.2026",
    owner: "Anna Wróbel",
    recruitments: 6,
    rate: "125 zł/h",
    english: "C1",
    availability: "3 miesiące",
    workMode: "3 dni/tydz. z biura",
    nationality: "Polska",
    skills: ["Java", "Spring Framework", "Hibernate", "SQL", "Angular", "React", "Microservices"],
    headline: "5+ lat komercyjnego doświadczenia w Javie, m.in. w Goldman Sachs. Frontend w Angular i React.",
    lastNote: "Doświadczenie w sektorze bankowym (Goldman Sachs). Otwarty na projekty fintech, preferuje Warszawę.",
    rejectionReason: "Po CV — za długi okres wypowiedzenia (3 miesiące).",
    added: "23.06.2026",
  },
  {
    id: "marek",
    name: "Marek Pastuszczak",
    initials: "MP",
    role: "Fullstack Developer",
    location: "Warszawa",
    email: "marek.pastuszczak@gmail.com",
    phone: "+48 692 145 908",
    stage: "new",
    stageDate: "7.07.2026",
    owner: "Martyna Golańska",
    recruitments: 12,
    rate: "122,5 zł/h",
    english: "C1",
    availability: "od zaraz",
    workMode: "3 dni/tydz. z biura",
    nationality: "Polska",
    skills: ["Java", "Spring", "Microservices", "REST", "OpenAPI", "React", "TypeScript", "Angular"],
    headline: "Backend Java z frontendem w React/TypeScript, 4 lata doświadczenia, architektura mikroserwisowa.",
    lastNote: "Klient PL_CSP — proponujemy stawkę 178 zł/h na rolę full-stack. Czekamy na potwierdzenie dostępności.",
    added: "21.05.2026",
  },
  {
    id: "sebastian",
    name: "Sebastian Mazur",
    initials: "SM",
    role: "Backend Developer (Java)",
    location: "Kraków",
    email: "sebastian.mazur@gmail.com",
    phone: "+48 693 550 118",
    stage: "interview",
    stageDate: "5.07.2026",
    owner: "Sandra Strzelak",
    recruitments: 14,
    rate: "140 zł/h",
    english: "B2",
    availability: "1 miesiąc",
    workMode: "Zdalnie",
    nationality: "Polska",
    skills: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker", "Kubernetes"],
    headline: "Backend Java z mocnym doświadczeniem w chmurze AWS i konteneryzacji.",
    lastNote: "Bardzo dobre spotkanie — świetne dopasowanie do zespołu płatności. Rekomendacja na rozmowę techniczną.",
    added: "14.05.2026",
  },
  {
    id: "katarzyna",
    name: "Katarzyna Wiśniewska",
    initials: "KW",
    role: "Frontend Developer (React)",
    location: "Wrocław",
    email: "k.wisniewska@gmail.com",
    phone: "+48 501 223 660",
    stage: "acceptance",
    stageDate: "4.07.2026",
    owner: "Marta Kozarewicz",
    recruitments: 3,
    rate: "115 zł/h",
    english: "C1",
    availability: "2 tygodnie",
    workMode: "Zdalnie",
    nationality: "Polska",
    skills: ["React", "TypeScript", "Next.js", "Redux", "GraphQL", "Jest"],
    headline: "Frontend React/Next.js z 6-letnim doświadczeniem, silna w wydajności i dostępności.",
    lastNote: "Zaakceptowała warunki, czekamy na podpisanie oferty. Bardzo zmotywowana.",
    added: "28.06.2026",
  },
  {
    id: "pawel",
    name: "Paweł Nowak",
    initials: "PN",
    role: "DevOps Engineer",
    location: "Warszawa",
    email: "pawel.nowak@proton.me",
    phone: "+48 660 774 201",
    stage: "screening",
    stageDate: "6.07.2026",
    owner: "Anna Wróbel",
    recruitments: 8,
    rate: "160 zł/h",
    english: "B2",
    availability: "od zaraz",
    workMode: "Hybryda",
    nationality: "Polska",
    skills: ["Kubernetes", "Terraform", "AWS", "GitLab CI", "Ansible", "Python"],
    headline: "DevOps z 7-letnim doświadczeniem, IaC i platformy Kubernetes na dużą skalę.",
    lastNote: "Umówiony na screening telefoniczny w czwartek o 10:00. Bardzo dobre pierwsze wrażenie.",
    added: "1.07.2026",
  },
  {
    id: "anna",
    name: "Anna Zielińska",
    initials: "AZ",
    role: "QA Automation Engineer",
    location: "Poznań",
    email: "anna.zielinska@gmail.com",
    phone: "+48 512 908 337",
    stage: "hired",
    stageDate: "20.06.2026",
    owner: "Martyna Golańska",
    recruitments: 2,
    rate: "105 zł/h",
    english: "C1",
    availability: "—",
    workMode: "Hybryda",
    nationality: "Polska",
    skills: ["Selenium", "Playwright", "Java", "TestNG", "CI/CD", "Cypress"],
    headline: "QA Automation z 5-letnim doświadczeniem, frameworki Playwright i Selenium.",
    lastNote: "Start 1.07 — onboarding zaplanowany, dokumenty podpisane. Wszystko gotowe.",
    added: "12.05.2026",
  },
  {
    id: "krzysztof",
    name: "Krzysztof Lewandowski",
    initials: "KL",
    role: "Java Developer",
    location: "Gdańsk",
    email: "k.lewandowski@wp.pl",
    phone: "+48 605 118 442",
    stage: "rejected",
    stageDate: "27.06.2026",
    owner: "Sandra Strzelak",
    recruitments: 5,
    rate: "95 zł/h",
    english: "B1",
    availability: "od zaraz",
    workMode: "Zdalnie",
    nationality: "Polska",
    skills: ["Java", "Spring", "MySQL", "JUnit"],
    headline: "Java mid z 3-letnim doświadczeniem, solidne podstawy backendu.",
    lastNote: "Poziom angielskiego poniżej wymagań klienta — projekt wymaga swobodnej komunikacji w C1.",
    rejectionReason: "Po rozmowie — angielski na poziomie B1 zamiast wymaganego C1.",
    added: "18.06.2026",
  },
  {
    id: "magdalena",
    name: "Magdalena Dąbrowska",
    initials: "MD",
    role: "Fullstack Developer",
    location: "Łódź",
    email: "m.dabrowska@gmail.com",
    phone: "+48 517 664 090",
    stage: "screening",
    stageDate: "6.07.2026",
    owner: "Marta Kozarewicz",
    recruitments: 7,
    rate: "128 zł/h",
    english: "C1",
    availability: "3 tygodnie",
    workMode: "Hybryda",
    nationality: "Polska",
    skills: ["Java", "Spring Boot", "React", "TypeScript", "Docker", "Azure"],
    headline: "Fullstack Java + React z 5-letnim doświadczeniem, projekty oparte o Azure.",
    lastNote: "Pozytywny pierwszy kontakt, otwarta na hybrydę w Warszawie. Umawiamy screening.",
    added: "2.07.2026",
  },
];
