"""Build and atomically cut over Voyage 4 Qdrant collections.

Examples:
    python -m scripts.migrate_voyage4 build --commit
    python -m scripts.migrate_voyage4 validate --gold-set-report /secure/gold.json
    python -m scripts.migrate_voyage4 bootstrap-aliases
    python -m scripts.migrate_voyage4 switch --gold-set-report /secure/gold.json
    python -m scripts.migrate_voyage4 rollback --targets-json '{...}'

``switch`` never deletes the old collections. Keep them for at least 14 days.
The gold-set report must be generated by the production matching evaluator and
contain ``{"passed": true}``; a missing report fails closed.
"""

from __future__ import annotations

import argparse
import asyncio
from collections import defaultdict
import hashlib
import json
import logging
from pathlib import Path
import sys
from typing import Iterable, Optional

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from sqlalchemy import func, select  # noqa: E402

from app.core.config import settings  # noqa: E402
from app.core.database import AsyncSessionLocal  # noqa: E402
from app.models.candidate import Candidate  # noqa: E402
from app.models.competence_category import CandidateCompetenceCategory  # noqa: E402
from app.models.embedding_index_queue import EmbeddingIndexQueue  # noqa: E402
from app.models.job import Job  # noqa: E402
from app.models.talent_pool import TalentPoolMembership  # noqa: E402
from app.services.embedding_service import (  # noqa: E402
    _build_candidate_text_v2,
    _build_job_text_v2,
    _voyage_embed_batch,
)
from app.services.qdrant_factory import (  # noqa: E402
    ACTIVE_ALIASES,
    VOYAGE4_TEXT_V2,
    get_qdrant_client,
    physical_collections,
)
from app.services.qdrant_migration import (  # noqa: E402
    alias_targets,
    ensure_physical_collections,
    rollback_aliases,
    switch_aliases,
    validate_physical_collections,
)

logger = logging.getLogger("migrate_voyage4")


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


async def _upsert(collection: str, points: list[dict]) -> None:
    if not points:
        return
    from qdrant_client.models import PointStruct

    client = get_qdrant_client(timeout=60)
    await asyncio.to_thread(
        client.upsert,
        collection_name=collection,
        points=[PointStruct(**point) for point in points],
        wait=True,
    )


async def _build_entities(
    entity: str,
    rows: list[object],
    *,
    batch_size: int,
    collection: str,
) -> tuple[int, int]:
    builder = _build_candidate_text_v2 if entity == "candidates" else _build_job_text_v2
    succeeded = failed = 0
    for offset in range(0, len(rows), batch_size):
        batch = rows[offset : offset + batch_size]
        texts = [builder(row) for row in batch]
        selected = [(row, text) for row, text in zip(batch, texts) if text.strip()]
        failed += len(batch) - len(selected)
        if not selected:
            continue
        embeddings = await _voyage_embed_batch(
            [text for _, text in selected],
            input_type="document",
            model=VOYAGE4_TEXT_V2.model,
            dimension=VOYAGE4_TEXT_V2.dimension,
        )
        if embeddings is None:
            failed += len(selected)
            continue
        points: list[dict] = []
        for (row, text), embedding in zip(selected, embeddings):
            if embedding is None:
                failed += 1
                continue
            point_id = int(getattr(row, "id"))
            payload = {
                f"{entity[:-1]}_id": point_id,
                "source_hash": _hash(text),
                "text_schema": VOYAGE4_TEXT_V2.text_schema,
                "model": VOYAGE4_TEXT_V2.model,
            }
            if entity == "jobs":
                payload["client_id"] = getattr(row, "client_id", None)
                payload["industry"] = getattr(row, "industry", None) or ""
            points.append({"id": point_id, "vector": embedding, "payload": payload})
        await _upsert(collection, points)
        succeeded += len(points)
        logger.info("%s progress=%s/%s", entity, offset + len(batch), len(rows))
    return succeeded, failed


def _mean_vector(vectors: Iterable[list[float]]) -> Optional[list[float]]:
    rows = list(vectors)
    if not rows:
        return None
    dimension = len(rows[0])
    if dimension != VOYAGE4_TEXT_V2.dimension or any(
        len(row) != dimension for row in rows
    ):
        raise RuntimeError("centroid input contains a mismatched vector dimension")
    return [sum(row[index] for row in rows) / len(rows) for index in range(dimension)]


async def _build_centroid_collection(
    collection: str,
    groups: dict[int, list[int]],
    *,
    candidate_collection: str,
) -> int:
    client = get_qdrant_client(timeout=60)
    points: list[dict] = []
    written = 0
    for group_id, candidate_ids in groups.items():
        rows = []
        unique_ids = sorted(set(candidate_ids))
        for offset in range(0, len(unique_ids), 256):
            rows.extend(
                await asyncio.to_thread(
                    client.retrieve,
                    collection_name=candidate_collection,
                    ids=unique_ids[offset : offset + 256],
                    with_payload=False,
                    with_vectors=True,
                )
            )
        centroid = _mean_vector(
            row.vector for row in rows if isinstance(row.vector, list)
        )
        if centroid is None:
            continue
        member_hash = _hash(
            ",".join(str(value) for value in sorted(set(candidate_ids)))
        )
        points.append(
            {
                "id": int(group_id),
                "vector": centroid,
                "payload": {"source_hash": member_hash, "members": len(rows)},
            }
        )
        if len(points) >= 100:
            written += len(points)
            await _upsert(collection, points)
            points = []
    written += len(points)
    await _upsert(collection, points)
    return written


async def _source_rows(
    limit: Optional[int] = None,
) -> tuple[list[Candidate], list[Job]]:
    async with AsyncSessionLocal() as db:
        candidate_stmt = select(Candidate).order_by(Candidate.id)
        job_stmt = select(Job).order_by(Job.id)
        if limit is not None:
            candidate_stmt = candidate_stmt.limit(limit)
            job_stmt = job_stmt.limit(limit)
        candidates = list((await db.scalars(candidate_stmt)).all())
        jobs = list((await db.scalars(job_stmt)).all())
    return candidates, jobs


async def _centroid_groups(
    indexed_candidates: Optional[set[int]] = None,
) -> tuple[dict[int, list[int]], dict[int, list[int]]]:
    async with AsyncSessionLocal() as db:
        cc_rows = (
            await db.execute(
                select(
                    CandidateCompetenceCategory.competence_category_id,
                    CandidateCompetenceCategory.candidate_id,
                )
            )
        ).all()
        pool_rows = (
            await db.execute(
                select(
                    TalentPoolMembership.talent_pool_id,
                    TalentPoolMembership.candidate_id,
                )
            )
        ).all()
    cc: dict[int, list[int]] = defaultdict(list)
    pools: dict[int, list[int]] = defaultdict(list)
    for group_id, candidate_id in cc_rows:
        if indexed_candidates is None or int(candidate_id) in indexed_candidates:
            cc[int(group_id)].append(int(candidate_id))
    for group_id, candidate_id in pool_rows:
        if indexed_candidates is None or int(candidate_id) in indexed_candidates:
            pools[int(group_id)].append(int(candidate_id))
    return (
        {key: values for key, values in cc.items() if values},
        {key: values for key, values in pools.items() if values},
    )


async def build(
    *, commit: bool, batch_size: int, limit: Optional[int], recreate: bool
) -> dict:
    client = get_qdrant_client(timeout=60)
    targets = (
        ensure_physical_collections(client, recreate=recreate)
        if commit
        else physical_collections()
    )
    candidates, jobs = await _source_rows(limit)
    expected = {
        "candidates": sum(
            bool(_build_candidate_text_v2(row).strip()) for row in candidates
        ),
        "jobs": sum(bool(_build_job_text_v2(row).strip()) for row in jobs),
    }
    if not commit:
        return {"dry_run": True, "expected": expected, "targets": targets}
    if not recreate:
        populated = {
            entity: int(client.get_collection(collection).points_count or 0)
            for entity, collection in targets.items()
            if int(client.get_collection(collection).points_count or 0) > 0
        }
        if populated:
            raise SystemExit(
                f"blue collections are not empty: {populated}; pass --recreate"
            )

    candidate_ok, candidate_failed = await _build_entities(
        "candidates",
        candidates,
        batch_size=batch_size,
        collection=targets["candidates"],
    )
    job_ok, job_failed = await _build_entities(
        "jobs", jobs, batch_size=batch_size, collection=targets["jobs"]
    )
    if limit is not None:
        return {
            "partial": True,
            "candidates": {"ok": candidate_ok, "failed": candidate_failed},
            "jobs": {"ok": job_ok, "failed": job_failed},
        }

    indexed_candidates = {
        int(row.id) for row in candidates if _build_candidate_text_v2(row).strip()
    }
    cc_groups, pool_groups = await _centroid_groups(indexed_candidates)
    cc_count = await _build_centroid_collection(
        targets["cc_centroids"],
        cc_groups,
        candidate_collection=targets["candidates"],
    )
    pool_count = await _build_centroid_collection(
        targets["pool_centroids"],
        pool_groups,
        candidate_collection=targets["candidates"],
    )
    return {
        "partial": False,
        "candidates": {"ok": candidate_ok, "failed": candidate_failed},
        "jobs": {"ok": job_ok, "failed": job_failed},
        "cc_centroids": cc_count,
        "pool_centroids": pool_count,
    }


def _gold_passed(path: Path) -> bool:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("passed") is True


async def validation_inputs() -> tuple[dict[str, int], dict[str, dict[int, str]], int]:
    candidates, jobs = await _source_rows()
    candidate_docs = [
        (int(row.id), _build_candidate_text_v2(row)) for row in candidates
    ]
    job_docs = [(int(row.id), _build_job_text_v2(row)) for row in jobs]
    indexed_candidates = {point_id for point_id, text in candidate_docs if text.strip()}
    cc_groups, pool_groups = await _centroid_groups(indexed_candidates)
    expected_counts = {
        "candidates": sum(bool(text.strip()) for _, text in candidate_docs),
        "jobs": sum(bool(text.strip()) for _, text in job_docs),
        "cc_centroids": len(cc_groups),
        "pool_centroids": len(pool_groups),
    }
    sample_hashes = {
        "candidates": {
            point_id: _hash(text) for point_id, text in candidate_docs if text.strip()
        },
        "jobs": {point_id: _hash(text) for point_id, text in job_docs if text.strip()},
        "cc_centroids": {
            group_id: _hash(",".join(str(value) for value in sorted(set(members))))
            for group_id, members in cc_groups.items()
        },
        "pool_centroids": {
            group_id: _hash(",".join(str(value) for value in sorted(set(members))))
            for group_id, members in pool_groups.items()
        },
    }
    sample_hashes = {
        entity: dict(list(values.items())[:10])
        for entity, values in sample_hashes.items()
    }
    async with AsyncSessionLocal() as db:
        backlog = int(
            await db.scalar(
                select(func.count(EmbeddingIndexQueue.id)).where(
                    EmbeddingIndexQueue.status.in_(("pending", "processing", "retry"))
                )
            )
            or 0
        )
    return expected_counts, sample_hashes, backlog


async def validate(gold_set_report: Path) -> list[dict]:
    expected, samples, backlog = await validation_inputs()
    results = validate_physical_collections(
        get_qdrant_client(timeout=60),
        expected_counts=expected,
        sample_hashes=samples,
        outbox_backlog=backlog,
        gold_set_passed=_gold_passed(gold_set_report),
    )
    return [result.__dict__ for result in results]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    build_parser = sub.add_parser("build")
    build_parser.add_argument("--commit", action="store_true")
    build_parser.add_argument("--recreate", action="store_true")
    build_parser.add_argument("--batch", type=int, default=128)
    build_parser.add_argument("--limit", type=int)
    for command in ("validate", "switch"):
        item = sub.add_parser(command)
        item.add_argument("--gold-set-report", type=Path, required=True)
    sub.add_parser("bootstrap-aliases")
    rollback = sub.add_parser("rollback")
    rollback.add_argument("--targets-json", required=True)
    return parser.parse_args()


async def main() -> int:
    logging.basicConfig(level=logging.INFO)
    args = _parse_args()
    if args.command == "build":
        if not 1 <= args.batch <= 128:
            raise SystemExit("--batch must be between 1 and 128")
        output = await build(
            commit=args.commit,
            batch_size=args.batch,
            limit=args.limit,
            recreate=args.recreate,
        )
    elif args.command == "validate":
        output = await validate(args.gold_set_report)
    elif args.command == "bootstrap-aliases":
        current = {
            "candidates": settings.QDRANT_COLLECTION,
            "jobs": settings.QDRANT_JOBS_COLLECTION,
            "cc_centroids": settings.QDRANT_CC_CENTROIDS_COLLECTION,
            "pool_centroids": settings.QDRANT_POOL_CENTROIDS_COLLECTION,
        }
        client = get_qdrant_client(timeout=60)
        if alias_targets(client):
            raise SystemExit("active aliases already exist")
        switch_aliases(client, current, expected_current={})
        output = {"aliases": alias_targets(client)}
    elif args.command == "switch":
        validation = await validate(args.gold_set_report)
        client = get_qdrant_client(timeout=60)
        previous = alias_targets(client)
        if set(previous) != set(ACTIVE_ALIASES.values()):
            raise SystemExit("run bootstrap-aliases before switch")
        switch_aliases(client, physical_collections(), expected_current=previous)
        output = {
            "validation": validation,
            "rollback_targets": previous,
            "active": alias_targets(client),
            "retain_previous_until_days": 14,
            "required_runtime_env": {
                "VOYAGE_MODEL": VOYAGE4_TEXT_V2.model,
                "EMBEDDING_TEXT_SCHEMA": VOYAGE4_TEXT_V2.text_schema,
                "QDRANT_COLLECTION": ACTIVE_ALIASES["candidates"],
                "QDRANT_JOBS_COLLECTION": ACTIVE_ALIASES["jobs"],
                "QDRANT_CC_CENTROIDS_COLLECTION": ACTIVE_ALIASES["cc_centroids"],
                "QDRANT_POOL_CENTROIDS_COLLECTION": ACTIVE_ALIASES["pool_centroids"],
            },
        }
    else:
        client = get_qdrant_client(timeout=60)
        current = alias_targets(client)
        rollback_targets = json.loads(args.targets_json)
        rollback_aliases(client, rollback_targets, expected_current=current)
        output = {"active": alias_targets(client)}
    print(json.dumps(output, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
