// AUTO-GENERATED from backend OpenAPI by scripts/generate-analytics-types.mjs.
// Do not edit this file by hand; run `npm run analytics:types:generate`.

export type AnalyticsPeriodKind = "day" | "week" | "month" | "quarter" | "year" | "custom"

export interface AnalyticsPeriodSchema {
  kind: AnalyticsPeriodKind
  start: string
  end: string
  timezone?: string
}

export interface AnalyticsQuality {
  status?: AnalyticsQualityStatus
  warnings?: string[]
  source_watermarks?: Record<string, string | null>
}

export type AnalyticsQualityStatus = "complete" | "partial" | "unavailable"

export interface CallsData {
  completed: number | null
  inbound: number | null
  outbound: number | null
  total_duration_seconds: number | null
  average_duration_seconds: number | null
}

export interface ClientFinanceData {
  client_id: number
  client_name: string
  active_contracts: number
  incomplete_contracts: number
  totals: FinanceTotals
}

export interface ClientOperationsData {
  client_id: number
  client_name: string
  jobs_total: number
  jobs_open: number
  pipeline_pairs: number
  placements: number
  active_contracts: number
}

export interface DeliveryLeadPerformanceData {
  delivery_leads: DeliveryLeadPerformanceRow[]
}

export interface DeliveryLeadPerformanceRow {
  user_id: number
  user_name: string
  jobs: number
  verifications: number
  recommendations: number
  placements: number
}

export interface ExecutiveBoardData {
  overview: OverviewData
  finance: FinanceSummaryData
  tenders: TendersData
}

export interface FinanceClientRow {
  client_id: number
  client_name: string
  active_contracts: number
  incomplete_contracts: number
  totals: FinanceTotals
}

export interface FinanceClientsData {
  clients: FinanceClientRow[]
}

export interface FinanceSummaryData {
  report_date: string
  active_contracts: number
  incomplete_contracts: number
  totals: FinanceTotals
}

export interface FinanceTotals {
  revenue: string | null
  costs: string | null
  margin: string | null
  margin_pct: number | null
  currency?: string
}

export interface FinanceTrendData {
  months: FinanceTrendPoint[]
}

export interface FinanceTrendPoint {
  month: string
  active_contracts: number
  incomplete_contracts: number
  totals: FinanceTotals
}

export interface FinancialAdjustmentRow {
  id: number
  adjustment_date: string
  category: string
  description: string
  amount: string
  currency: string
  amount_pln: string | null
  fx_rate: string | null
  fx_date: string | null
  status: FinancialAdjustmentStatus
  created_by_user_id: number
  approved_by_user_id: number | null
  approved_at: string | null
  created_at: string
  updated_at: string
}

export interface FinancialAdjustmentsData {
  adjustments: FinancialAdjustmentRow[]
}

export type FinancialAdjustmentStatus = "draft" | "approved"

export interface KpiTargets {
  calls_daily: number
  verifications_daily: number
  candidates_added_daily: number | null
  placements_monthly: number
  precision_pct: number
}

export interface MetricDefinition {
  key: string
  label: string
  definition: string
  source: string
  timezone?: string
}

export interface MetricsMetaData {
  metric_version?: string
  interval_semantics?: string
  definitions: MetricDefinition[]
}

export interface OverviewCandidates {
  total: number
  active: number
}

export interface OverviewClients {
  total: number
  active: number
}

export interface OverviewContracts {
  active: number
  expiring_30_days: number
  incomplete_date_data: number
}

export interface OverviewData {
  candidates: OverviewCandidates
  jobs: OverviewJobs
  clients: OverviewClients
  contracts: OverviewContracts
  pipeline: OverviewPipeline
}

export interface OverviewJobs {
  total: number
  open: number
}

export interface OverviewPipeline {
  placements: number
}

export interface PersonalKpiData {
  calls_completed: number | null
  calls_available: boolean
  verifications: number
  candidates_added: number
  recommendations: number
  placements: number
  precision_30d: PrecisionMetric
  targets: KpiTargets
}

export interface PipelineSnapshotData {
  total_pairs: number
  stages: StageCount[]
}

export interface PrecisionMetric {
  value_pct: number | null
  verified: number
  recommended: number
  window_days?: number
}

export interface RecentHire {
  candidate_id: number
  candidate_name: string
  job_id: number
  job_title: string
  client_id: number
  client_name: string
  hired_at: string
}

export interface RecentHiresData {
  hires: RecentHire[]
}

export interface RecruitmentFunnelData {
  verified: number
  recommended: number
  internal_interview: number
  client_interview: number
  placed: number
}

export interface RecruitmentUserData {
  user_id: number
  user_name: string
  primary_role: string
  kpis: PersonalKpiData
}

export interface SourceMetric {
  source: string
  cohort_candidates: number
  placed_by_period_end: number
  hire_rate_pct: number
}

export interface SourcesData {
  attribution?: string
  sources: SourceMetric[]
}

export interface StageCount {
  stage: string
  candidates: number
}

export interface TeamCallRow {
  user_id: number
  user_name: string
  completed: number
  total_duration_seconds: number
  average_duration_seconds: number | null
}

export interface TeamCallsData {
  users: TeamCallRow[]
}

export interface TeamKpiRow {
  user_id: number
  user_name: string
  primary_role: string
  calls_completed: number | null
  calls_available: boolean
  verifications: number
  candidates_added: number
  recommendations: number
  placements: number
  targets: KpiTargets
}

export interface TeamKpisData {
  users: TeamKpiRow[]
}

export interface TenderRow {
  job_id: number
  job_title: string
  client_id: number
  client_name: string
  outcome: string
  event_at: string
}

export interface TendersData {
  total: number
  won: number
  lost: number
  pending: number
  unknown: number
  win_rate_pct: number | null
  tenders: TenderRow[]
}
